# Generated by Django 2.2.3 on 2019-11-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
