# Generated by Django 2.2.3 on 2019-11-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0002_auto_20191121_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='ischeckedin',
            field=models.BooleanField(default=False),
        ),
    ]
