# Generated by Django 2.2.7 on 2019-11-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0003_visitor_ischeckedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
