# Generated by Django 2.2.7 on 2019-11-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0004_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='checkout',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
