# Generated by Django 2.2.7 on 2019-11-21 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0005_auto_20191121_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitor',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
