# Generated by Django 2.2.7 on 2019-11-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0006_auto_20191121_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='created',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='checkin',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='checkout',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
